### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by krytarowski** [freenode/ircd-seven#116]
I'm attempting to package ircd-seven (charybdis) for NetBSD in pkgsrc.

GitHub ships with old tags.

Upstream (?) site with distfiles is dead.

FreeBSD packages 3.5.3... on GitHub 3.4.2?

The most recent tag is 5 years old.

**Comment by shadowcat-mst** [comment]
I'm not sure why you're trying to package freenode's designed-for-us-and-us-alone charybdis derived ircd? Are you sure you didn't mean to package the actual charybdis ircd?

**Comment by krytarowski** [comment]
I'm packaging it on a user request.

**Comment by AbstractBeliefs** [comment]
I think we should clarify: ircd-seven is basically a freenode-specific fork of charybdis that we develop in the open as we believe in open source and our users being able to see how the software they use works, and possibly contribute.

It's not really intended for repackaging for public use, these users would be better served by upstream charybdis instead, though we won't stop you.

**Comment by krytarowski** [comment]
I will bring this to this user and ask for being certain. That upstream charybdis seems to be dead..

**Comment by krytarowski** [comment]
Hmm, there is also something in https://github.com/charybdis-ircd/charybdis

**Comment by shadowcat-mst** [comment]
Just be aware we've never released a version in the first place, as such - what version we deploy is handled by our deployment setup. So version numbers, tags etc. aren't really going to be a thing in this repository.

**Comment by krytarowski** [comment]
The user is fine with https://github.com/charybdis-ircd/charybdis

Thanks for feedback!
