### ISSUE TITLE
UMODE +R confusing to newcomers?

### ISSUE THREAD

**Issue by dylnmc** [freenode/ircd-seven#142]
Hi,

I was told that it may be of use to put in my two cents here. I remember--a while ago--I used to get private messages from newcomers asking why they can't talk in channels that have `+q $~a` (which quiets all users who are not logged). I would assume that now that `+R` is set by default for everyone on freenode that this might increase the number of confused newcomers trying who can neither talk on such a `+q $~a`'d channel nor send a PRIVMSG to any of the participants (since probably most of them will have `+R`).

I have no facts nor figures. It is just a thought. Probably most of them will find their way to `#freenode` and ask why they're not able to send messages to the channel. Hopefully, they will get the appropriate answers there. I just had this tiny concern about setting `+R` to everyone by default. I wouldn't know the proper solution since there are ... other unfortunate issues that require the settings to be the way they are, but I am merely bringing it up here ... well, because I was told to :smiley:

Long live freenode,
dylnmc

**Comment by ilbelkyr** [comment]
Since `+R` is no longer a default user mode, I'm closing this for now. Thank you for your concern, though!
