### ISSUE TITLE
--disable-hyperscan broken

### ISSUE THREAD

**Issue by xnrand** [freenode/ircd-seven#153]
https://github.com/freenode/ircd-seven/blob/51749efad96bd861271a860a345a6823aeb3c9c0/configure.ac#L524-L528

The configure script gives a choice on whether hyperscan support should be enabled. However, even if `--disable-hyperscan` is passed to the configure script, the resulting makefiles will still attempt to build `m_filter` and fail if there is no hyperscan on the system.

In my opinion, the autotools files should either be changed to properly build seven without `m_filter` if `--disable-hyperscan` is passed – or throw an error at configure time when attempting to build without hyperscan.

**Comment by thecodezero** [comment]
Hi, @xnrand ,
sudo apt-get install libhyperscan-dev pkg-config
will help you get rid of it.

**Comment by ilbelkyr** [comment]
We should allow building without hyperscan (at the cost of not building `m_filter`), IMO; the rest of the ircd still works fine without it. I'm not the best at autotools but I'll take a look.

**Comment by PoolloverNathan** [comment]
> Hi, @xnrand ,
> sudo apt-get install libhyperscan-dev pkg-config
> will help you get rid of it.
```
E: Unable to locate package libhyperscan-dev
```
```
pi@PI-NATHAN:~/ircd-seven $ uname -a
Linux PI-NATHAN 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
```

**Comment by edk0** [comment]
Hyperscan doesn't support anything expect x86 and amd64.
