### ISSUE TITLE
Cannot compile "fatal error: hs_common.h: No such file or directory"

### ISSUE THREAD

**Issue by CoNFiDeNTHaKaN** [freenode/ircd-seven#154]
Hi, 

I was facing "fatal error: hs_common.h: No such file or directory" error message when i try to compile ircd-seven on Ubuntu 18.10.

Solution:
You must install libhyperscan-dev  and pkg-config to get rid of it!

sudo apt-get install libhyperscan-dev pkg-config

Special Thanks to @mquin  for the valuable help. ( staff of freenode )

**Comment by thecodezero** [comment]
Hi, this issue must be closed, and this solution should be in-turn be added to other related pull requests about this error.

**Comment by ilbelkyr** [comment]
The `--disable-hyperscan` configure flag is supposed to avoid this issue, but currently doesn't.

Closing as duplicate of #153.
