### ISSUE TITLE
Not able to see the changes file though `dput <ppa> <changes>` is successfully completed

### ISSUE THREAD

**Issue by AnitaNayak** [freenode/ircd-seven#163]
My launchpad id is anitanayak. Though I am able to build and push the changes file to my ppa from command line, the same I am not able to view in my ppa `changed files`. hence I am not able to trigger the build. Can anyone help me?

**Comment by equinox** [comment]
Hi there.

After reading the referenced issue, it's clear you were after help with launchpad-related software, but you've came to the wrong place. This is freenode's repository for their IRCd, what you're actually after is joining the freenode IRC network and asking your question in #launchpad/#launchpad-dev.

To do this, you'll need an IRC client such as webchat.freenode.net or kiwi.freenode.net. Either works. The aforementioned launchpad-related channels however require you to be identified to services, so if you've not done that before, a guide to that can be found [here](https://freenode.net/kb/answer/registration).

If you need further help regarding this or using the freenode IRC network, I'd suggest connecting via one of those clients I listed above and joining the #freenode channel.
