### ISSUE TITLE
RPL_LOCALUSERS and RPL_GLOBALUSERS

### ISSUE THREAD

**Issue by eskimo** [freenode/ircd-seven#183]
Doesn't this violate protocol to have a space before the colon?

I mean, it does kinda look silly as well to be
`86008 87738 Current global users 86008, max 87738` 

https://github.com/freenode/ircd-seven/blob/87e23a1b9c4e4be329775f328af6de882999bcf5/src/messages.tab#L289,L290

**Comment by ilbelkyr** [comment]
> Doesn't this violate protocol to have a space before the colon?

[Nope.][rfc1459-message-format]

> I mean, it does kinda look silly as well to be
> `86008 87738 Current global users 86008, max 87738`

That's a matter of how the client displays it. The redundancy is awkward but does allow the human-readable part to be useful without needing to interpret any of the non-final parameters. In any case, there's precedent as we didn't come up with [the format][ircdocs-rpl-localusers].

[rfc1459-message-format]: https://tools.ietf.org/html/rfc1459#section-2.3.1
[ircdocs-rpl-localusers]: https://defs.ircdocs.horse/defs/numerics.html#rpl-localusers-265

**Comment by eskimo** [comment]
Interesting. I saw my client parsed it weird and decided to check around a bunch of other networks and couldn't find another that sent it the same. Was this changed somewhat recently?

**Comment by ilbelkyr** [comment]
It seems to date back to ircd-hybrid, so probably not. I think all charybdis (and related) networks send it this way.

**Comment by eskimo** [comment]
Odd. I must've changed something on my end that made it break these types of messages. Thanks for clarifying.
