### ISSUE TITLE
Add websocket support

### ISSUE THREAD

**Issue by Shou** [freenode/ircd-seven#2]
This would allow people to connect from the web browser without any plugins like Java. There are C libraries for this already, but should a re-implementation be needed the protocol is pretty simple.

**Comment by spb** [comment]
This is something that should be implemented in Charybdis first, at which point we'll pick it up in the next feature pull.

**Comment by Mikaela** [comment]
If I have understood correctly, Charybdis is not developed any more than Atheme and only (security) bug fixes are accepted.

**Comment by Shou** [comment]
I've made an issue on the Charybdis repository, so we'll see.
