### ISSUE TITLE
Possible segmentation fault during a remote MODRESTART.

### ISSUE THREAD

**Issue by mniip** [freenode/ircd-seven#21]
A MODRESTART reloads all modules, including `m_encap.so`. However if the MODRESTART command came from a server (in an ENCAP), we will have `ms_encap` in the call stack. Unless a lucky coincidence occurs, the modules will be loaded at different addresses, and the call stack will  become corrupt, segfaulting the ircd upon return from the command handling code.

**Comment by edk0** [comment]
MODUNLOADing m_encap.so will reliably crash the ircd too.

**Comment by kaniini** [comment]
I shot myself in the foot with a 12 gauge shotgun, can you guys fix that too?

**Comment by kaniini** [comment]
(In all seriousness `m_encap` should probably be a protected module.)
