### ISSUE TITLE
Strip out 0x1D as a part of color strip

### ISSUE THREAD

**Issue by Svetlana-T** [freenode/ircd-seven#24]
I got a "there is a way to sneak italics into the topic since ircd doesn't yet know about 0x1D" in #freenode; I believe the same remark might apply to +c channel mode. Haven't tested it though.

**Comment by ilbelkyr** [comment]
As far as I can tell, 545f0a0f0 already fixed this. Testing verifies that the character isn't allowed in topics nor messages filtered by `+c`.
