### ISSUE TITLE
Feature Request: mark messages only shown due to +z

### ISSUE THREAD

**Issue by Fuchs** [freenode/ircd-seven#30]
It would be great if ops could what messages they are only able to see due to the channelmode +z being set. 

How has to be discussed, of course it would be nice if it didn't break clients or protocol and doesn't require much work for clients to understand it.

**Comment by mquin** [comment]
An option could be to make use of the @#channel format used when sending messages to all operators - as that is effectively what a user subject to +z is doing.

At a glance it looks like it could be done with a simple change to sendto_channel_opmod().

**Comment by Fuchs** [comment]
Yes, the major "downside" of this option is that few clients still don't handle these properly (e.g. show them as a query / private message etc.)

I think most are covered by now, but some are not. And as this is not staff-only, if we change it, we should certainly announce / document that somewhere  (and maybe inform the channels that we know go sometimes +zq $~a) 

Otherwise that certainly would be better than the current state, thanks for looking and implementing a possible fix 👍

**Comment by mquin** [comment]
I suppose the client compatibility concerns could be addressed by making this a client capability.

**Comment by ilbelkyr** [comment]
For reference, this has been implemented and announced to be enabled 2019-07-31 (unconditionally, as further discussed internally).
